/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import model.ModelNotifikasi;

/**
 *
 * @author usER
 */
public class Notifications extends javax.swing.JPanel {

    /**
     * Creates new form Notifications
     */
    private ModelNotifikasi modelNotifikasi;
    public Notifications(ModelNotifikasi modelNotifikasi) {
        initComponents();
        this.modelNotifikasi = modelNotifikasi;
        info();
    }
        
    private void info() {
        LocalDate date = modelNotifikasi.getTanggalNotifikasi().toLocalDate();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd MMM yyyy", Locale.of("id", "ID"));
        lbTgl.setText(dateFormatter.format(date));
        
        lbNama.setText(modelNotifikasi.getNamaNotifikasi());
        
        StringBuilder row1 = new StringBuilder();
        StringBuilder row2 = new StringBuilder();
        String description = modelNotifikasi.getDeskripsi();
        Pattern pattern = Pattern.compile("berhasil");
        Matcher matcher = pattern.matcher(description);
        
        
        if(matcher.find()) {
            int index = description.indexOf("berhasil");
            row1.append(description.substring(0, index).trim());
            lbRow1.setText(row1.toString());
            
            int startIndex = description.indexOf("berhasil");
            row2.append(description.substring(startIndex));
            lbRow2.setText(row2.toString());
        } else {
            int index = description.indexOf("pasien");
            row1.append(description.substring(0, index).trim());
            lbRow1.setText(row1.toString());
            
            int startIndex = description.indexOf("pasien");
            row2.append(description.substring(startIndex));
            lbRow2.setText(row2.toString());
        }
        
        LocalTime time = modelNotifikasi.getTanggalNotifikasi().toLocalTime();
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm", Locale.of("id", "ID"));
        lbWaktu.setText(timeFormatter.format(time));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTgl = new javax.swing.JLabel();
        lbWaktu = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        lbRow1 = new javax.swing.JLabel();
        lbRow2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(185, 185, 185)));

        lbTgl.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbTgl.setForeground(new java.awt.Color(0, 0, 0));
        lbTgl.setText("Tanggal Notifikasi");

        lbWaktu.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lbWaktu.setForeground(new java.awt.Color(0, 0, 0));
        lbWaktu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbWaktu.setText("Waktu Notifikasi");

        lbNama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNama.setForeground(new java.awt.Color(0, 0, 0));
        lbNama.setText("Nama Notifikasi");

        lbRow1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lbRow1.setForeground(new java.awt.Color(0, 0, 0));
        lbRow1.setText("Harga Beli Posh Men Perfum Spary Red Extreme150ML");

        lbRow2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lbRow2.setForeground(new java.awt.Color(0, 0, 0));
        lbRow2.setText("berhasil dirubah dari 1000 menjadi 5000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRow2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbRow1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                .addComponent(lbNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTgl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRow1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRow2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbWaktu))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbRow1;
    private javax.swing.JLabel lbRow2;
    private javax.swing.JLabel lbTgl;
    private javax.swing.JLabel lbWaktu;
    // End of variables declaration//GEN-END:variables
}
